runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  memory_gb: 1
env_variables:
  NODE_ENV: production 
  MONGODB_URI: mongodb+srv://admin:@15011Badillo@cluster0.0p0o2by.mongodb.net/?retryWrites=true&w=majority
